### ISSUE TITLE
node-webkit中出现的问题

### ISSUE THREAD

**Issue by susamcsx** [xiangshouding/node-pngquant-native#10]
Uncaught Error: Can't load the addon. Issue to: https://github.com/xiangshouding/node-pngquant-native/issues Error: Module did not self-register.
    at Error (native)
    at process.module.(anonymous function) [as dlopen](ATOM_SHELL_ASAR.js:140:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node](ATOM_SHELL_ASAR.js:140:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (E:\electron-v0.36.1-win32-x64\hello\node_modules\node-pngquant-native\binding.js:75:34)
    at Module._compile (module.js:425:26)

您好，请问这是什么问题呢？放在node命令行环境中可以运行，但是到了nw环境下就报这个错误了

**Comment by xiangshouding** [comment]
因为 node 和 nw 用的 v8 的内核应该是不一样的吧；你确认一下 v8 的版本；
