### ISSUE TITLE
Cannot load the addon

### ISSUE THREAD

**Issue by hrefhref** [xiangshouding/node-pngquant-native#20]
```
/data/node_modules/node-pngquant-native/binding.js:66
throw new Error('Can\'t load the addon. Issue to: ' + bugUrl);
^

Error: Can't load the addon. Issue to: https://github.com/xiangshouding/node-pngquant-native/issues
    at Object.<anonymous> (/data/node_modules/node-pngquant-native/binding.js:66:7)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data/node_modules/node-pngquant-native/index.js:1:77)
    at Module._compile (module.js:569:30)
```

debian stretch, node 8.x.

**Comment by xiangshouding** [comment]
正在支持，稍等。

**Comment by cfxmj2014** [comment]
现在支持了吗？

**Comment by ArtemOliinyk** [comment]
Still opened?
