### ISSUE TITLE
请支持 node V4.0.0

### ISSUE THREAD

**Issue by beanlee** [xiangshouding/node-pngquant-native#7]
升级node v4.0.0报错，希望能解决一下
Error: Can't load the addon. Issue to: https://github.com/xiangshouding/node-pngquant-native/issues
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\node_modules\node-pngquant-native\bindi
ng.js:61:7)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\node_modules\jnode-pngquant-native\index
.js:1:77)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

**Comment by xiangshouding** [comment]
好的，我研究一下；
